// <auto-generated />
using System;
using FastWorkshops.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastWorkshops.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtaColaborador", b =>
                {
                    b.Property<int>("AtasId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradoresId")
                        .HasColumnType("int");

                    b.HasKey("AtasId", "ColaboradoresId");

                    b.HasIndex("ColaboradoresId");

                    b.ToTable("AtaColaboradores", (string)null);
                });

            modelBuilder.Entity("FastWorkshops.Domain.Entities.Ata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId")
                        .IsUnique();

                    b.ToTable("Atas", (string)null);
                });

            modelBuilder.Entity("FastWorkshops.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Colaboradores", (string)null);
                });

            modelBuilder.Entity("FastWorkshops.Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DataRealizacao");

                    b.HasIndex("Nome");

                    b.ToTable("Workshops", (string)null);
                });

            modelBuilder.Entity("AtaColaborador", b =>
                {
                    b.HasOne("FastWorkshops.Domain.Entities.Ata", null)
                        .WithMany()
                        .HasForeignKey("AtasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastWorkshops.Domain.Entities.Colaborador", null)
                        .WithMany()
                        .HasForeignKey("ColaboradoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastWorkshops.Domain.Entities.Ata", b =>
                {
                    b.HasOne("FastWorkshops.Domain.Entities.Workshop", "Workshop")
                        .WithOne("Ata")
                        .HasForeignKey("FastWorkshops.Domain.Entities.Ata", "WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("FastWorkshops.Domain.Entities.Workshop", b =>
                {
                    b.Navigation("Ata");
                });
#pragma warning restore 612, 618
        }
    }
}
